default_language_version:
  python: python3.8
repos:
  - hooks:
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
  - hooks:
      - id: isort
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
  - hooks:
      - id: black
        name: black
    repo: https://github.com/psf/black
    rev: 22.3.0
  - hooks:
      - id: flake8
    repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
  - hooks:
      - additional_dependencies:
          - types-PyYAML
          - types-requests
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
