on: ["push", "pull_request"]

name: Test

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
              python-version: 3.8

        - name: Install Dependencies
          run: pip install .[lint]

        - name: Run Black
          run: black --check .

        - name: Run flake8
          run: flake8 .

        - name: Run isort
          run: isort --check-only .

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
              python-version: 3.8

        - name: Install Dependencies
          run: pip install .[lint,test]  # Might need test deps

        - name: Run MyPy
          run: mypy .